FROM arm32v7/openjdk:11-jre-slim
WORKDIR /home/mycollections
COPY build/libs/mycollections-1.0.0-all.jar ./mycollections.jar
EXPOSE 8080
CMD ["java", "-Dcom.sun.management.jmxremote", "-Xmx256m", "-XX:+IdleTuningGcOnIdle", "-Xtune:virtualized", "-jar", "mycollections.jar"]