FROM arm32v7/adoptopenjdk:15-jdk-hotspot-focal
WORKDIR /home/mycollections
COPY build/libs/*.jar ./mycollections.jar
EXPOSE 8443
CMD ["java", "-Dcom.sun.management.jmxremote", "-Xmx256m", "-jar", "mycollections.jar"]
