micronaut:
  application:
    name: bonjour-software-limited-mycollections
  router:
    static-resources:
      main:
        paths: classpath:static
        mapping: /**
  security:
    enabled: true
    intercept-url-map:
      - pattern: /**
        httpMethod: GET
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
        get-allowed: true
  ssl:
    enabled: true
    build-self-signed: true
mongo:
  user: '${MONGODB_USER}'
  password: '${MONGODB_PASSWORD}'
  host: '${MONGODB_HOST}'
  database: 'mycollections'
notification:
  type: 'email'
  apiKey: '${NOTIFICATION_API_KEY}'
  target: '${NOTIFICATION_TARGET}'
host:
  domain: '${HOST_DOMAIN}'
username:
  allowed-suffixes: '${USERNAME_ALLOWED_SUFFIXES}'