micronaut:
  application:
    name: bjrsft-labs-mycollections
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://accounts.google.com'
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: '${JWT_SIGNATURES_SECRET}'
    endpoints:
      logout:
        enabled: true
        get-allowed: true
datasources:
  default:
    url: jdbc:postgresql:postgres
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'